"""Validated species-level distributional trait inference."""

from .diversity import categorical_diversity, gini_simpson
from .geometry import (
    AlignmentNullResult,
    TwoModeResult,
    alignment_statistic,
    hellinger_rows,
    one_vs_rest_contrast,
    permute_rows_within_strata,
    structured_alignment_null,
    two_mode_axis,
)
from .reliability import ReliabilityResult, observer_disjoint_reliability
from .spatial import (
    AssociationResult,
    continuous_spatial_permutation_null,
    continuous_spatial_rho,
    distribution_spatial_association,
    great_circle_pairwise_km,
    jensen_shannon_pairwise,
    matched_difference_spatial_permutation_null,
    matched_difference_spatial_rho,
    pairwise_absolute_difference,
    partial_distribution_spatial_association,
    partial_rank_correlation,
    spatial_permutation_null,
    spatial_permutation_null_from_distance_matrix,
    spatial_rho,
    spatial_rho_from_distance_matrix,
    species_equal_spatial_omnibus,
)

__all__ = [
    "AlignmentNullResult",
    "AssociationResult",
    "ReliabilityResult",
    "TwoModeResult",
    "alignment_statistic",
    "categorical_diversity",
    "continuous_spatial_permutation_null",
    "continuous_spatial_rho",
    "distribution_spatial_association",
    "gini_simpson",
    "great_circle_pairwise_km",
    "hellinger_rows",
    "jensen_shannon_pairwise",
    "matched_difference_spatial_permutation_null",
    "matched_difference_spatial_rho",
    "observer_disjoint_reliability",
    "pairwise_absolute_difference",
    "one_vs_rest_contrast",
    "partial_distribution_spatial_association",
    "partial_rank_correlation",
    "permute_rows_within_strata",
    "spatial_permutation_null",
    "spatial_permutation_null_from_distance_matrix",
    "spatial_rho",
    "spatial_rho_from_distance_matrix",
    "species_equal_spatial_omnibus",
    "structured_alignment_null",
    "two_mode_axis",
]
