#!/usr/bin/env python3
from __future__ import annotations

import re
from pathlib import Path

path = Path("docs/jbi_manuscript_editorial_revision.md")
text = path.read_text(encoding="utf-8")


def replace_once(old: str, new: str) -> None:
    global text
    count = text.count(old)
    if count != 1:
        raise SystemExit(f"Expected one occurrence, found {count}: {old[:120]!r}")
    text = text.replace(old, new, 1)


replace_once(
    "We combined audited literature classifications with GBIF occurrences and WorldClim 2.1 data.",
    "We combined source-traceable, rule-derived literature classifications with GBIF occurrences and WorldClim 2.1 data.",
)

section_pattern = re.compile(
    r"(?ms)^### Literature discovery and validation\n.*?(?=^### Occurrence data and sampling sensitivity\n)"
)
matches = section_pattern.findall(text)
if len(matches) != 1:
    raise SystemExit(f"Expected one literature/classification section; found {len(matches)}")

replacement = """### Literature discovery and validation

Initial automated discovery queried the OpenAlex works index (Priem et al., 2022) using eight English-language search expressions: `\"flower color polymorphism\"`, `\"flower colour polymorphism\"`, `\"floral color polymorphism\"`, `\"floral colour polymorphism\"`, `\"flower color variation\" pollinator`, `\"flower colour variation\" pollinator`, `\"floral color morph\"` and `\"floral colour morph\"`. The implemented defaults retrieved up to two cursor-paginated pages of 200 records for each query. Work identifiers were deduplicated across queries.

Candidate binomials were matched against the repository angiosperm census. A species mention was retained only when the binomial occurred in the title or within a 220-character window around flower-, colour-, pigment-, morph- or polymorphism-related language in an available abstract. Strong flower-colour context increased the evidence score; titles indicating genomes, transcriptomes, checklists, floras or other contexts unlikely to document natural flower-colour variation were penalized. Candidate evidence required a score of at least eight. Source titles, DOI or OpenAlex identifiers and supporting text were retained for traceability. Subsequent targeted scripts searched unresolved or high-priority species and fed the resolved review queue.

Repository history records automated global discovery and targeted follow-up or enrichment activity from 16 to 19 July 2026 (Appendix S1). The first global output was committed on 16 July; deferred-candidate follow-up and evidence aggregation occurred on 16–17 July; and targeted enrichment of confirmed cases with ambiguous spatial evidence was committed on 19 July. No explicit language filter was coded, and the English search phrases and dependence on indexed title and abstract metadata may have produced language and database-coverage bias.

### Classification of spatial organization

Spatial labels were generated by rule-based screening of retained source text. The baseline classifier concatenated the retained title, evidence passage and review-reason fields and searched prespecified regular expressions for within-population and geographic-differentiation language. A within-population label was assigned when a within-population signal occurred without a geographic signal; an among-population label was assigned for the converse; simultaneous signals produced `mixed`, and absence of both produced `unclear`. Mixed and unclear rows were flagged as requiring manual review and excluded from binary comparative models. The implementation explicitly describes these automated labels as screening labels rather than final biological annotations.

The resolved evidence queue retained `review_status = unreviewed`, and the repository contains no field documenting completed independent human screening, duplicate review, inter-reviewer agreement or formal adjudication for every included binary classification. We therefore report the within- and among-population states as source-traceable, rule-derived classifications. We do not claim that they are independently human-screened annotations; any human inspection conducted outside the repository cannot be reconstructed from the available record.

Source identifiers, evidence snippets and rule-derived decision notes were propagated into the analysis dataset and checked for traceability. A targeted rule audit detected that the phrase `within populations` had not been recognized by the initial expression. The rule was corrected and the analysis was rerun; a case with signals at both spatial scales was consequently moved to `mixed` and removed from the binary baseline set. The final baseline-unambiguous manifest was frozen without reference to the climatic model results and has SHA-256 digest `416949addd664d6e89230df00fc1e89adad261b51268f24f60cd42770559e217`. The manifest contains 34 model-eligible species from 25 families: 20 within-population and 14 among-population cases. The retained correction-log table contains no post-freeze changes.

A broader evidence set supplemented ambiguous baseline records with automated high-confidence enrichment. Eligible enrichment records required a direct colour signal, no artificial signal and an evidence score of at least 20. Within- and among-population signals were aggregated by species; enrichment never erased an unambiguous baseline label, and conflicting signals produced `mixed`. At the minimum 20-cell threshold, the broader set contained 51 species from 29 families: 33 within-population and 18 among-population cases. The 17 enrichment-only species comprised 13 within-population and four among-population cases; this subset was below the prespecified minimum of 20 species and was not fitted as an independent model.

"""
text = section_pattern.sub(replacement, text, count=1)

replacements = {
    "### Audited baseline association": "### Baseline-unambiguous association",
    "The audited comparison identified a negative association": "The source-traceable baseline comparison identified a negative association",
    "The audited evidence suggests": "The source-traceable evidence suggests",
    "The audited baseline-unambiguous set": "The baseline-unambiguous set",
    "the audited baseline-unambiguous set": "the baseline-unambiguous set",
    "the audited baseline moisture-breadth estimate": "the baseline-unambiguous moisture-breadth estimate",
    "the audited baseline estimate": "the baseline-unambiguous estimate",
}
for old, new in replacements.items():
    text = text.replace(old, new)

text = text.replace(
    "Correcting one unrecognized plural phrase moved a species with evidence at both spatial scales out of the binary baseline set and changed the focal estimate.",
    "Correcting one unrecognized plural phrase in the rule set moved a species with signals at both spatial scales out of the binary baseline set and changed the focal estimate.",
)

if re.search(r"\baudited\b", text, flags=re.IGNORECASE):
    found = sorted(set(re.findall(r".{0,50}\baudited\b.{0,80}", text, flags=re.IGNORECASE)))
    raise SystemExit(f"Residual audited wording remains: {found}")

required = [
    "source-traceable, rule-derived literature classifications",
    "review_status = unreviewed",
    "screening labels rather than final biological annotations",
    "no field documenting completed independent human screening",
    "direct colour signal, no artificial signal and an evidence score of at least 20",
    "### Baseline-unambiguous association",
]
for phrase in required:
    if phrase not in text:
        raise SystemExit(f"Missing classification-transparency phrase: {phrase}")

path.write_text(text, encoding="utf-8")
print("classification transparency integrated")
